image: Visual Studio 2019
version: 3.4.3.{build}
install:
- ps: >-
    nuget install Build\.nuget\packages.config -OutputDirectory packages

    nuget restore FileHelpers.sln
nuget:
  project_feed: true

build: off

test_script:
- ps: >-
    cd Build
    
    ./build.ps1

artifacts:

- path: Output/*.nupkg
