image: Visual Studio 2019

install:
- ps: >-
    gitversion /l console /output buildserver

nuget:
  project_feed: true

before_build:
- ps: >-
    nuget restore FileHelpers.sln

build_script:
- ps: >-
    cd Build    
    ./build.ps1

artifacts:
- path: Output/*.nupkg
